### ISSUE TITLE
Attempted import error: 'Source' is not exported from '@graphql-toolkit/common'

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [kamilkisiela/graphql-config#529]
How to reproduce:

```ts
import { loadConfigSync } from 'graphql-config';
const config = loadConfigSync({});
```

Output:

```
Failed to compile.

./node_modules/graphql-config/index.esm.js
Attempted import error: 'Source' is not exported from '@graphql-toolkit/common'.
```

**Comment by kamilkisiela** [comment]
https://github.com/kamilkisiela/graphql-config-529
https://codesandbox.io/s/pedantic-sara-mdg4y?file=/src/index.js

I checked and it works, could you create a reproduction?

**Comment by FluorescentHallucinogen** [comment]
This is a ES Module bug. I'm facing this problem in TS projects. The simplest way to reproduce the bug is to use `create-react-app` template:

`npx create-react-app my-app --template typescript` (`yarn create react-app my-app --template typescript`) or even `npx create-react-app my-app` (`yarn create react-app my-app`).

Your repro uses `require` syntax instead of `import`.

**Comment by FluorescentHallucinogen** [comment]
Found something very similar: https://github.com/ardatan/graphql-toolkit/pull/574.

@ardatan, cc.

**Comment by kamilkisiela** [comment]
https://github.com/kamilkisiela/graphql-config-529/commit/03a4a538c834adebb7d3252a6129c829efe8e4ef

Once you provide a reproduction, as I asked I will reopen the issue

**Comment by dotansimha** [comment]
@FluorescentHallucinogen 

In open-source, there is a "contract" that says that we’ll develop and improve it for free, and will always try to support you in any issue.

The return for that is to report issues, and help us reproduce it.
If it's something that is not simple for us to reproduce, we'll need you to help us, because creating the reproduction is eventually for you, in order to get this fixed, for you.

GitHub issues are all about collaboration, it's not a ticketing or support system, you should either be involved (by reporting, creating reproduction or even PRs) or use a different library that works for you.

Do you expect someone to create a project, try to setup everything, just to get to the same place you got? Why not just share your current status with us, as-is?

**Comment by FluorescentHallucinogen** [comment]
@dotansimha I know what open source is and how it works, because I'm also an open source contributor, just like you. This bug report is a part of my effort to create a pull request that fixes an issue https://github.com/zth/vscode-graphiql-explorer/issues/10 opened by me as continuation of my work in the previous pull request https://github.com/zth/vscode-graphiql-explorer/pull/9. This is the work that I do for free in my free time because I want to improve this project for the benefit of the whole community.

I truly believed that reproduction _steps_ I provided (one line command from https://github.com/kamilkisiela/graphql-config/issues/529#issuecomment-619839382 and two lines of code from https://github.com/kamilkisiela/graphql-config/issues/529#issue-607026120) is enought.

Anyway, I've created a reproduction _repository_:

https://github.com/FluorescentHallucinogen/graphql-config-529-repro

**Comment by dotansimha** [comment]
@FluorescentHallucinogen thank you so much.
This was not intended to harm or offend you, I truly believe that you know that maintaining open-source projects is not easy. From our experience, steps are not enough in most cases, because a lot can change, that's why we insist on reproduction.

**Comment by kamilkisiela** [comment]
[`v3.0.1`](https://github.com/kamilkisiela/graphql-config/releases/tag/v3.0.1)
